name: dependabot

on:
  pull_request_target:
    types:
      - closed

jobs:
  validate:
    uses: ./.github/workflows/test.yml
  dependabot:
    name: Dependabot Auto-merge
    runs-on: ubuntu-latest
    needs: [validate]
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == 'true'
    steps:
      - name: ğŸ’¿ Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GH_TOKEN }}

      - name: â†”ï¸ Enable Auto-merge for minor and patch Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
